config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'welcome/index'
 
  resources :articles do
    resources :comments
  end

  resources :user

  resources :leagues

  resources :matches

  resources :contacts

  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 5 }

    has_attached_file :image, styles: {large: "640x640>", medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end
    
    def new
        if signed_in?
            restrict_access if current_user.is_admin != true 
            @article = Article.new
        else 
            restrict_access
        end
    end

    def edit
        if signed_in?
            restrict_access if current_user.is_admin != true 
            @article = Article.find(params[:id])
        else 
            restrict_access
        end
    end

    def create
        @article = Article.new(article_params)
 
        if @article.save
            redirect_to articles_path 
        else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
        if signed_in?
            restrict_access if current_user.is_admin != true 
            @article = Article.find(params[:id])
            @article.destroy
            redirect_to articles_path
        else 
            restrict_access
        end
    end

    def restrict_access
        redirect_to root_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text, :image)
        end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, html: { multipart: true } do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edytuj Artykuł</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container text-center">

 
<h1>Archiwum</h1>


<div class="row">
  <% @articles.each do |article| %>
      <div class="col-lg-4 col-md-6 col-xs-12">
        <div class="jumbotron card border-dark">
          <%= image_tag article.image.url(:medium), :class=>"card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text"><%= article.text %></p>
            <span>
            <div class="btn btn-info"><%= link_to 'Więcej', article_path(article) %></div>
              <% if signed_in? %>
                <% if current_user.is_admin%>
                  <div class="btn btn-warning"><%= link_to 'Edytuj', edit_article_path(article) %></div>
                  <div class="btn btn-danger"><%= link_to 'Usuń', article_path(article),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></div>
                <% end %>
              <% end %>
            </span>
          </div>
        </div>
      </div>
  <% end %>
</div>
 

</div>

app/views/articles/new.html.erb
<h1>Dodaj artykuł</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="space"></div>

<div>
 
<div class="jumbotron card card-image">
  <div class="d-flex justify-content-center">
    <p>
      <h1><strong><%= @article.title %></strong></h1>
    </p>
  </div>



  <div class="d-flex justify-content-center">
    <div> 
      

      <p> <%= image_tag @article.image.url(:large) , :class=>"card-img-top" %> </p>
      
      <p>
        <strong>Text:</strong>
        <%= @article.text %>
      </p>
    </div>
  </div>
</div>
  <div class="jumbotron card card-image">
  <div>
    <h2>Komentarze</h2>
    <div class="space"></div>
    <%= render @article.comments %>
    <div class="space"></div>
      <h2>Dodaj komentarz:</h2>
      <%= render 'comments/form' %>

      <% if signed_in? %>
        <% if current_user.is_admin%>
          <%= link_to 'Edytuj artykuł', edit_article_path(@article) %>
        <% end %>
      <% end %>
  </div>
  </div>

</div>

<div class="space"></div>