config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'welcome/index'
 
  resources :articles do
    resources :comments
  end

  resources :user

  resources :leagues

  resources :matches

  resources :contacts

  root 'welcome#index'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :player_1, :class_name => 'User'
  belongs_to :player_2, :class_name => 'User'
  belongs_to :player_3, :class_name => 'User'
  belongs_to :player_4, :class_name => 'User'
  belongs_to :league, :class_name => 'League'

  filterrific(
   default_filter_params: { sorted_by: 'created_at_desc' },
   available_filters: [
     :sorted_by,
     :search_query,
     :with_match_id,
     :with_created_at_gte
   ]
 )

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    def index
        @matches = Match.all.paginate(page: params[:page],per_page: 6)
    end

    def show
        @match = Match.find(params[:id])
    end
     
    def new
        if signed_in?
            @match = Match.new
        else 
            restrict_access
        end
    end

    def create
        @match = Match.new(match_params)
 
        if @match.save
            redirect_to matches_path
        else
            render 'new'
        end
        
    end

    def destroy
        if signed_in?
            restrict_access if current_user.is_admin != true 
            @match = Match.find(params[:id])
            @match.destroy
            redirect_to matches_path
        else 
            restrict_access
        end
    end

    def restrict_access
        redirect_to root_path
    end

    private
        def match_params
            params.require(:match).permit(:player_1_id, :player_2_id, :player_3_id, :player_4_id, :player_1_score, :player_2_score, :player_3_score, :player_4_score, :league_id)
        end
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with model: @match do |form| %>

<% if @match.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@match.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @match.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 <div class="jumbo2 card card-image">
  <div class="form">
    <div class="row">
        <div class="col-md-offset-1 col-md-12 "><%= form.submit "Stwórz grę", class:"form-control" %></div>
    </div>
    <div class="row">
        <div class="col-md-2">Gracz:</div>
        <div class="col-md-4">Wynik:</div>
    </div>
    <div class="row">
        <div class="col-md-2"><%= collection_select(:match, :player_1_id, User.all,:id, :email,{}, {:class=>'form-control'}) %></div>
        <div class="col-md-4"><%= form.number_field :player_1_score, class:"form-control" %></div>
    </div>
    <div class="row">
        <div class="col-md-2"><%= collection_select(:match, :player_2_id, User.all,:id, :email,{}, {:class=>'form-control'}) %></div>
        <div class="col-md-4"><%= form.number_field :player_2_score, class:"form-control" %></div>
    </div>
    <div class="row">
        <div class="col-md-2"><%= collection_select(:match, :player_3_id, User.all,:id, :email,{}, {:class=>'form-control'}) %></div>
        <div class="col-md-4"><%= form.number_field :player_3_score, class:"form-control" %></div>
    </div>
    <div class="row">
        <div class="col-md-2"><%= collection_select(:match, :player_4_id, User.all,:id, :email,{}, {:class=>'form-control'}) %></div>
        <div class="col-md-4"><%= form.number_field :player_4_score, class:"form-control" %></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">Liga:</div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4"><%= collection_select(:match, :league_id, League.all,:id, :name,{}, {:class=>'form-control'}) %></div>
    </div>
  </div>
</div>

<% end %>

app/views/matches/index.html.erb
<h1>Lista meczy</h1>


<% @matches.each do |match| %>

<div class="jumbo2 card card">
  <div class="p-2">
    <div class="row border bg-light">
      <div class="col-sm-1">Data</div>
      <div class="col-sm"><%= match.created_at %></div>
    </div>
    <div class="row">
      <div class="col-sm-1 border bg-light">Gracze:</div>

      <%if User.find_by_id(match.player_1_id).username.blank?%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_1_id).email, user_path(User.find_by_id(match.player_1_id)) %></div>
      <%else%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_1_id).username, user_path(User.find_by_id(match.player_1_id)) %></div>
      <%end%>

      <%if User.find_by_id(match.player_2_id).username.blank?%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_2_id).email, user_path(User.find_by_id(match.player_2_id)) %></div>
      <%else%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_2_id).username, user_path(User.find_by_id(match.player_2_id)) %></div>
      <%end%>

      <%if User.find_by_id(match.player_3_id).username.blank?%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_3_id).email, user_path(User.find_by_id(match.player_3_id)) %></div>
      <%else%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_3_id).username, user_path(User.find_by_id(match.player_3_id)) %></div>
      <%end%>

      <%if User.find_by_id(match.player_4_id).username.blank?%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_4_id).email, user_path(User.find_by_id(match.player_4_id)) %></div>
      <%else%>
        <div class="col-sm-2"><%= link_to User.find_by_id(match.player_4_id).username, user_path(User.find_by_id(match.player_4_id)) %></div>
      <%end%>

    </div>
    <div class="row">
      <div class="col-sm-1 border bg-light">Wyniki:</div>
      <div class="col-sm-2"><%= match.player_1_score %></div>
      <div class="col-sm-2"><%= match.player_2_score %></div>
      <div class="col-sm-2"><%= match.player_3_score %></div>
      <div class="col-sm-2"><%= match.player_4_score %></div>
    </div>
    <div class="row">
      <div class="col-sm-1 border bg-light">Liga:</div>
      <div class="col-sm-2"><%=League.find_by_id(match.league_id).name %></div>
    </div>

    <div class="row">
      <% if signed_in? %>
        <% if current_user.is_admin%>
          <div class="btn btn-danger"><%= link_to 'Usuń', match_path(match),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></div>
        <% end %>
      <% end %>
      
    </div>

  </div>
</div>

<% end %>

<div class="jumbo2 card card">
<div class="row justify-content-center">
  <%= will_paginate @matches, previous_label:"Wstecz", next_label:"Do przodu"   %>
</div>
</div>

app/views/matches/new.html.erb
<h1>Dodaj nowy mecz</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>