config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'welcome/index'
 
  resources :articles do
    resources :comments
  end

  resources :user

  resources :leagues

  resources :matches

  resources :contacts

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 5 }

    has_attached_file :image, styles: {large: "640x640>", medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message
    attribute :nickname,  :captcha  => true
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "Zapytanie ze strony MahjongSite",
        :to => "waciriv144@eigoemail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/league.rb
class League < ApplicationRecord
    has_many :matches, :class_name => 'Match', :foreign_key => 'match_id'

    has_attached_file :image, styles: {large: "640x640>", medium: "300x300>", thumb: "100x100>", icon: "50x50" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :player_1, :class_name => 'User'
  belongs_to :player_2, :class_name => 'User'
  belongs_to :player_3, :class_name => 'User'
  belongs_to :player_4, :class_name => 'User'
  belongs_to :league, :class_name => 'League'

  filterrific(
   default_filter_params: { sorted_by: 'created_at_desc' },
   available_filters: [
     :sorted_by,
     :search_query,
     :with_match_id,
     :with_created_at_gte
   ]
 )

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :matches, :class_name => 'Match', :foreign_key => 'match_id'

  has_attached_file :image, styles: {large: "640x640>", medium: "300x300>", thumb: "100x100>", icon: "50x50" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

    def index
        if signed_in?
            @leagues = League.all
            @users = User.all
            @matches = Match.all

            @league_scores=Hash.new(0)

            @scores = Hash.new(0)

            @leagues.each do |league|
                
                @scores.clear

                @matches.each do |match|
                    if match.league_id==league.id
                        @scores[match.player_1_id]+=match.player_1_score
                        @scores[match.player_2_id]+=match.player_2_score
                        @scores[match.player_3_id]+=match.player_3_score
                        @scores[match.player_4_id]+=match.player_4_score
                    end
                end
                
                @league_scores[league.id]=@scores.deep_dup.delete_if {|key, value| value == 0 }
            end
        else
            restrict_access
        end
    end

    def show
        @league = League.find(params[:id])
    end

    def new
        if signed_in?
            restrict_access if current_user.is_admin != true 
            @league = League.new
        else 
            restrict_access
        end
    end

    def create
        @league = League.new(league_params)
 
        if @league.save
            redirect_to matches_path
        else
            render 'new'
        end
        
    end

    def restrict_access
        redirect_to root_path
    end

    private
        def league_params
            params.require(:league).permit(:name, :image, :start, :end)
        end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    def index
        @matches = Match.all.paginate(page: params[:page],per_page: 6)
    end

    def show
        @match = Match.find(params[:id])
    end
     
    def new
        if signed_in?
            @match = Match.new
        else 
            restrict_access
        end
    end

    def create
        @match = Match.new(match_params)
 
        if @match.save
            redirect_to matches_path
        else
            render 'new'
        end
        
    end

    def destroy
        if signed_in?
            restrict_access if current_user.is_admin != true 
            @match = Match.find(params[:id])
            @match.destroy
            redirect_to matches_path
        else 
            restrict_access
        end
    end

    def restrict_access
        redirect_to root_path
    end

    private
        def match_params
            params.require(:match).permit(:player_1_id, :player_2_id, :player_3_id, :player_4_id, :player_1_score, :player_2_score, :player_3_score, :player_4_score, :league_id)
        end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
        restrict_access if @user.id != current_user.id 
    end

    def update
        @user = User.find(params[:id])
       
        if @user.update(user_params)
          redirect_to @user
        else
          render 'edit'
        end
    end

    def restrict_access
      redirect_to root_path
    end

    private
        def user_params
        params.require(:user).permit(:username, :image, :email, :is_admin)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MahjongSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    	
    <meta name="viewport" content="initial-scale=1.0"/>
  </head>




  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand">
        <img src="https://www.singaporemint.com/media/catalog/product/cache/978d88c4fa4223d1f4b49319a9c20eba/F/5/F535-1_2.png" width="50" height="50" alt="">
      
    </a>
    <a class="navbar-brand">Poznański klub mahjonga </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">


          <li class="nav-item">
            <a class="nav-link" href=<%= welcome_index_path%>> Strona domowa </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href=<%= articles_path%>>Archiwum</a>
          </li>

          <% if signed_in? %>
            <% if current_user.is_admin%>
              <li class="nav-item">
                <a class="nav-link" href=<%= new_article_path%>>Nowy artykuł</a>
              </li>
            <% end %>
          <% end %>

          <% if signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href=<%= matches_path%>> Gry</a>
          </li>
          <% end %>
          
          <% if signed_in? %>
            <li class="nav-item">
              <a class="nav-link"href=<%= new_match_path%>>Nowa gra </a>
          </li>
          <% end %>

           <% if signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href=<%= leagues_path%>> Ligi</a>
          </li>
          <% end %>

          <li class="nav-item">
            <a class="nav-link" href=<%= new_contact_path%>>Kontakt</a>
          </li>

        </ul>
    <ul class="navbar-nav">
    
            <li class="nav-item">
              <% if signed_in? %>
                Zalogowany jako:  <%= link_to current_user.email, edit_user_path(current_user) %>
                <div class="btn btn-danger"> <%= link_to 'Wyloguj', sign_out_path, method: :delete %> </div>
              <% else %>
                <%= link_to 'Zaloguj', sign_in_path %>
              <% end %>

              <%if signed_in?%>
                <%= image_tag current_user.image.url(:icon) %>
              <%end%>

              <div id="flash">
                <% flash.each do |key, value| %>
                  <div class="flash <%= key %>"><%= value %></div>
                <% end %>
              </div> 
            </li>
    </ul>

    </div>
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>



<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">Testowa stronka ruby on rails:
    <a> Gałecki Bartosz</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->